### ISSUE TITLE
"DJSpinRhythm_Controller_h" error " expected ')' before '&' token "

### ISSUE THREAD

**Issue by Minothrsr** [dmadison/DJHero-SpinRhythm#5]
Oh hey! That's a very nice project you've made!

I got this error on "DJSpinRhythm_Controller_h" when compiling, it is my mistake or something? (I'm using a Leonardo btw, made a demo test and everything works ok) thx ^w^

![arch](https://user-images.githubusercontent.com/102561066/167740033-b7c5b4c3-1695-4e2c-b098-10c527cce304.PNG)

**Comment by dmadison** [comment]
Hi there. Make sure you have the correct version of the NintendoExtensionCtrl library installed.

**Comment by Minothrsr** [comment]
Hello again, It's fixed.
You are right! Turns out I had a different version installed instead of Version 0.7.4 as required. Maybe my mistake work as a reminder for those who got the same mistake as I did. It works perfectly now! 
thanks again for your hard work

**Comment by dmadison** [comment]
I'm glad you got it working. Enjoy!
